### ISSUE TITLE
demo project failing to launch, sbcl 2.4.5 , m3 mac

### ISSUE THREAD

**Issue by vxe** [dnaeon/cl-jingle#4]
```
% make demo
sbcl --eval '(ql:quickload :jingle.demo)' \
                --eval '(asdf:make :jingle.demo)' \
                --eval '(quit)'
This is SBCL 2.4.5, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "jingle.demo":
  Load 1 ASDF system:
    jingle.demo
; Loading "jingle.demo"
.
debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD tid=259 "main thread" RUNNING {7008390303}>:
  System "lack-app-directory" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE               ] Try again
  1: [ABORT                  ] Give up on "lack-app-directory"
  2:                           Give up on "jingle.demo"
  3: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
  4:                           Ignore runtime option --eval "(ql:quickload :jingle.demo)".
  5:                           Skip rest of --eval and --load options.
  6:                           Skip to toplevel READ/EVAL/PRINT loop.
  7: [EXIT                   ] Exit SBCL (calling #'EXIT, killing the process).

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "lack-app-directory")
   source: (CERROR "Try again" 'SYSTEM-NOT-FOUND :NAME NAME)
0] 

```

## install procedure
```
cd ~/quicklisp/local-projects &&  git clone https://github.com/dnaeon/cl-jingle.git
```

**Comment by vxe** [comment]
```
cd ~/quicklisp/local-projects && git clone https://github.com/fukamachi/lack.git && git clone https://github.com/dnaeon/clingon.git
```

**Comment by dnaeon** [comment]
Hey @vxe ,

These dependencies usually come from Quicklisp, so you don't have to manually clone each one.

Make sure that you have Quicklisp installed and it should work just fine.

**Comment by vxe** [comment]
@dnaeon thanks for the reply, I'm seeing an issue where the swagger-ui js is 404 from browser.  The test case I'm using is below


<img width="1291" alt="image" src="https://github.com/dnaeon/cl-jingle/assets/4325947/fb5c2c82-0174-48c0-93ae-8639e0e807b3">


any ideas what might be going on?

**Comment by dnaeon** [comment]
Hey there, I'm away from my computer for the next week, so I won't be able
to look into this one. Please ping me after a week or so, if you don't hear
back from me.

Thanks!

**Comment by vxe** [comment]
tried the docker demo, seems like giving 403? 

<img width="495" alt="image" src="https://github.com/dnaeon/cl-jingle/assets/4325947/04406fb7-b62e-44a6-abd0-5f4ec7bb186a">

this image was built with:

```
make demo-docker
docker run -p 5000:5000 cl-jingle:latest serve --address 0.0.0.0
```

**Comment by dnaeon** [comment]
Hey @vxe ,

I won't be able to look at this one soon (traveling), but when I find some spare time I'll check it out.

Thanks!

**Comment by dnaeon** [comment]
Hey @vxe ,

Just tested out the image produced by the `demo-docker` target and it works fine.

Have you made any local changes? I also don't see any 2.4.5 version of the `clfoundation/sbcl` image, so I guess you have some local changes in there, or using a custom image?

**Comment by vxe** [comment]
to rule out problem with my sbcl i did a fresh clean checkout , and still get 403:

https://github.com/dnaeon/cl-jingle/issues/4#issuecomment-2211643500

perhaps a permissions issue?  the other endpoints are also 403:

```
% curl -vvv --get http://localhost:5000/hello
*   Trying [::1]:5000...
* Connected to localhost (::1) port 5000
> GET /hello HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Length: 0
< Server: AirTunes/760.20.1
< 
* Connection #0 to host localhost left intact
```


the port does seem to up and running well:

```
% nc -v localhost 5000
Connection to localhost port 5000 [tcp/commplex-main] succeeded!
```

**Comment by vxe** [comment]
I did a `chown -R $USER .` in the root directory and its working, there is a permissions problem in the uploaded files
