### ISSUE TITLE
Concurrent requests?

### ISSUE THREAD

**Issue by fehmud** [dnaeon/cl-jingle#6]
Hello, since `*request*` and `*response*` are global variables, can we infer that Jingle does not support concurrent requests? Thank you.

**Comment by vindarel** [comment]
Hello, those dynamic bindings are thread-safe: https://www.sbcl.org/manual/#Special-Variables

It's a common pattern to have a global defvar, and to bind it in a new scope:

```lisp
(let ((*request* (current-request)))
  …)
```

web servers do that under the hood and expose higher level functions.

jingle/ningle/clack or again hunchentoot support concurrent requests.
